CREATE DATABASE CRICKET;
USE CRICKET;
CREATE TABLE PLAYER(
	JERSEY_NO SMALLINT NOT NULL,
    PLAYER_NAME CHARACTER(40) NOT NULL,
    TEAM CHARACTER(40) NOT NULL,
    PRIMARY KEY(JERSEY_NO, PLAYER_NAME)
);
INSERT INTO PLAYER VALUES(1,'KL RAHUL','INDIA');
INSERT INTO PLAYER VALUES(7,'MS DHONI','INDIA');
INSERT INTO PLAYER VALUES(8,'RAVINDRA JADEJA','INDIA');
INSERT INTO PLAYER VALUES(18,'VIRAT KOHLI','INDIA');
INSERT INTO PLAYER VALUES(45,'ROHIT SHARMA','INDIA');
INSERT INTO PLAYER VALUES(17,'RISHABH PANT','INDIA');
INSERT INTO PLAYER VALUES(41,'SHREYAS IYER','INDIA');
INSERT INTO PLAYER VALUES(99,'RAVICHANDRAN ASHWIN','INDIA');
INSERT INTO PLAYER VALUES(33,'HARDIK PANDYA','INDIA');
INSERT INTO PLAYER VALUES(77,'SHUBMAN GILL','INDIA');
INSERT INTO PLAYER VALUES(27,'AJINKYA RAHANE','INDIA');
INSERT INTO PLAYER VALUES(25,'CHETESHWAR PUJARA','INDIA');

CREATE TABLE RUN(
	JERSEY_NO SMALLINT REFERENCES PLAYER,
    PLAYER_NAME CHARACTER(40) REFERENCES PLAYER,
    AGAINST_TEAM CHARACTER(40) NOT NULL,
    RUNS INT NOT NULL
);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (1,'KL RAHUL','ENGLAND',199), (1,'KL RAHUL','AUSTRALIA',102), (1,'KL RAHUL','SOUTH AFRICA',35);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (7,'MS DHONI','ENGLAND',42), (7,'MS DHONI','AUSTRALIA',77), (7,'MS DHONI','SOUTH AFRICA',55);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (8,'RAVINDRA JADEJA','ENGLAND',77), (8,'RAVINDRA JADEJA','AUSTRALIA',35), (8,'RAVINDRA JADEJA','SOUTH AFRICA',45);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (18,'VIRAT KOHLI','ENGLAND',35), (18,'VIRAT KOHLI','AUSTRALIA',24), (18,'VIRAT KOHLI','SOUTH AFRICA',118);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (45,'ROHIT SHARMA','ENGLAND',202), (45,'ROHIT SHARMA','AUSTRALIA',20), (45,'ROHIT SHARMA','SOUTH AFRICA',80);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (17,'RISHABH PANT','ENGLAND',67), (17,'RISHABH PANT','AUSTRALIA',156), (17,'RISHABH PANT','SOUTH AFRICA',117);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (41,'SHREYAS IYER','ENGLAND',30), (41,'SHREYAS IYER','AUSTRALIA',78), (41,'SHREYAS IYER','SOUTH AFRICA',82);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (99,'RAVICHANDRAN ASHWIN','ENGLAND',42), (99,'RAVICHANDRAN ASHWIN','AUSTRALIA',35), (99,'RAVICHANDRAN ASHWIN','SOUTH AFRICA',65);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (33,'HARDIK PANDYA','ENGLAND',25), (33,'HARDIK PANDYA','AUSTRALIA',82), (33,'HARDIK PANDYA','SOUTH AFRICA',64);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (77,'SUBHMAN GILL','ENGLAND',70), (77,'SUBHMAN GILL','AUSTRALIA',27), (77,'SUBHMAN GILL','SOUTH AFRICA',89);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (27,'AJINKYA RAHANE','ENGLAND',135), (27,'AJINKYA RAHANE','AUSTRALIA',80), (27,'AJINKYA RAHANE','SOUTH AFRICA',72);
INSERT INTO RUN (JERSEY_NO, PLAYER_NAME, AGAINST_TEAM, RUNS) VALUES (25,'CHETESWAR PUJARA','ENGLAND',204), (25,'CHETESWAR PUJARA','AUSTRALIA',72), (25,'CHETESWAR PUJARA','SOUTH AFRICA',125);

SELECT * FROM PLAYER;
SELECT * FROM RUN;

#FIND THE DETAILS OF THE PLAYERS WHOSE JERSEY NUMBER IS 18
SELECT * FROM PLAYER WHERE JERSEY_NO=18;

#FIND THE PLAYER WHO HAVE SCORED HIGHEST RUN
SELECT JERSEY_NO,PLAYER_NAME FROM RUN WHERE RUNS IN (SELECT MAX(RUNS) FROM RUN);

#FIND THE PLAYERS WHO HAVE MADE 100 RUNS
SELECT JERSEY_NO,PLAYER_NAME,RUNS,AGAINST_TEAM FROM RUN WHERE RUNS>=100;

#FIND THE PLAYER WHO HAVE MADE MORE THAN 200 RUNS AGAINST ENGLAND
SELECT JERSEY_NO,PLAYER_NAME,RUNS FROM RUN WHERE AGAINST_TEAM='ENGLAND' AND RUNS>=200;

#FIND THE DETAILS OF THE PLAYER 'KOHLI'
SELECT PLAYER.JERSEY_NO,PLAYER.PLAYER_NAME,RUNS,AGAINST_TEAM FROM RUN,PLAYER WHERE RUN.JERSEY_NO=PLAYER.JERSEY_NO AND PLAYER.PLAYER_NAME LIKE '%KOHLI';
