CREATE DATABASE CUSTOMER;
USE CUSTOMER;
CREATE TABLE CUSTOMER(
	CID VARCHAR(10) PRIMARY KEY,
    CNAME CHARACTER(40) NOT NULL,
    CAREA CHARACTER(40) NOT NULL,
    CAGE INT NOT NULL
);
INSERT INTO CUSTOMER VALUES('C001','RAMESH HALDER','KOLKATA',24);
INSERT INTO CUSTOMER VALUES('C002','RAJESH SARKAR','BARDDHAMAN',25);
INSERT INTO CUSTOMER VALUES('C003','ANIMESH SHARMA','ODISHA',23);
INSERT INTO CUSTOMER VALUES('C004','PIYALI SAMANTA','NEW DELHI',28);
INSERT INTO CUSTOMER VALUES('C005','HEMANTA CHAKRABORTY','KOLKATA',26);
INSERT INTO CUSTOMER VALUES('C006','PIYUSH GHOSH','HYDERABAD',28);

CREATE TABLE PURCHASE(
	CID VARCHAR(10) REFERENCES CUSTOMER,
    ITEM_NAME VARCHAR(40) NOT NULL,
    ITEM_TYPE CHARACTER(40) NOT NULL,
    PUR_DATE DATE NOT NULL,
    QTY INT NOT NULL,
    AMOUNT FLOAT NOT NULL
);
INSERT INTO PURCHASE (CID, ITEM_NAME, ITEM_TYPE, PUR_DATE, QTY, AMOUNT) VALUES ('C001','IPHONE 15 PRO MAX','ELECTRONIC GADGET','2023-12-26',1,156900.00), ('C001','FIRE-BOLTT SMART WATCH','ELECTRONIC GADGET','2023-12-26',1,1799.00);
INSERT INTO PURCHASE (CID, ITEM_NAME, ITEM_TYPE, PUR_DATE, QTY, AMOUNT) VALUES ('C002','ROTI MAKER','KITCHEN ACCESSORIES','2023-12-24',2,2299.00), ('C002','NON-STICK KADAI','KITCHEN ACCESSORIES','2023-12-25',1,1800.00);
INSERT INTO PURCHASE VALUES ('C003','TRIMMER MEN','ELECTRONIC GADGET','2023-12-26',2,3699.00);
INSERT INTO PURCHASE (CID, ITEM_NAME, ITEM_TYPE, PUR_DATE, QTY, AMOUNT) VALUES ('C004','SOFA SET','FURNITURE','2023-12-24',2,18000.00), ('C004','CHAIRS AND DESKS','FURNITURE','2023-12-28',1,5000.00);
INSERT INTO PURCHASE (CID, ITEM_NAME, ITEM_TYPE, PUR_DATE, QTY, AMOUNT) VALUES ('C005','TRAIN TICKET','TRAVEL','2023-12-25',4,600.00), ('C005','WATERPROOF BACKPACKS','TRAVEL','2023-12-25',2,1500.00);
INSERT INTO PURCHASE (CID, ITEM_NAME, ITEM_TYPE, PUR_DATE, QTY, AMOUNT) VALUES ('C006','MENS AND WOMENS CLOTHES','FASHION & BEAUTY','2023-12-27',7,3000.00), ('C006','MENS AND WOMENS SNEAKERS','FASHION & BEAUTY','2023-12-27',4,2000.00);

SELECT * FROM CUSTOMER;
SELECT * FROM PURCHASE;

#FIND THE CUSTOMERS WHOSE NAME ENDS WITH THE LETTER 'A'
SELECT CID,CNAME FROM CUSTOMER WHERE CNAME LIKE '%A';

#FIND THE CUSTOMERS WHOSE AGE IS WITHIN 20 TO 25 YEARS
SELECT CID,CNAME,CAGE FROM CUSTOMER WHERE CAGE>=20 AND CAGE<=25;

#FIND THE CUSTOMERS IN ODISHA WHO HAVE PURCHASED ELECTRONIC ITEMS
SELECT CUSTOMER.CID,CNAME,ITEM_NAME,ITEM_TYPE FROM CUSTOMER,PURCHASE WHERE CUSTOMER.CID=PURCHASE.CID AND CAREA='ODISHA' AND ITEM_TYPE='ELECTRONIC GADGET';

#FIND THE DETAILS WHO HAVE PURCHASED ITEM ON 25TH DECEMBER, 2023
SELECT PURCHASE.CID,CNAME,ITEM_NAME,PUR_DATE,QTY,AMOUNT FROM CUSTOMER,PURCHASE WHERE CUSTOMER.CID=PURCHASE.CID AND PUR_DATE='2023-12-25';

#CALCULATE THE AVERAGE PRICE OF ALL ELECTRONIC GADGETS OR TRAVEL ITEMS
SELECT ITEM_TYPE, ROUND(AVG(AMOUNT),2) AS "AVERAGE" FROM PURCHASE WHERE ITEM_TYPE='ELECTRONIC GADGET' OR ITEM_TYPE='TRAVEL' GROUP BY ITEM_TYPE;

#CHANGE THE PRICE OF 'TRAIN TICKET' TO RS 1000.00 /-
UPDATE PURCHASE SET AMOUNT=1000.00 WHERE ITEM_NAME='TRAIN TICKET';
SELECT * FROM PURCHASE;
