CREATE DATABASE DEPARTMENT;
USE DEPARTMENT;

CREATE TABLE DEPARTMENT(
	DEPT_NO VARCHAR(10) PRIMARY KEY,
    DEPT_NAME CHARACTER(40) NOT NULL
);

CREATE TABLE EMPLOYEE(
	EMP_NO VARCHAR(10) PRIMARY KEY,
    EMP_NAME CHARACTER(40) NOT NULL,
    CITY CHARACTER(40) NOT NULL,
    SALARY FLOAT NOT NULL,
    JOIN_DATE DATE NOT NULL,
    DEPT_NO VARCHAR(10) NOT NULL,
    FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO),
    CHECK(JOIN_DATE >= '2016-01-01')
);

INSERT INTO DEPARTMENT (DEPT_NO,DEPT_NAME) VALUES ('D001','MATHEMATICS'),('D002','PHYSICS'),('D003','CHEMISTRY'),('D004','GEOGRAPHY'),('D005','COMPUTER SCIENCE');

INSERT INTO EMPLOYEE (EMP_NO,EMP_NAME,CITY,SALARY,JOIN_DATE,DEPT_NO) VALUES 
		('EMP001','RAMCHARAN DAS','HYDERABAD',20000.00,'2018-12-18','D005'),
		('EMP002','KALICHARAN BOSE','BENGALURU',18000.00,'2021-07-05','D001'),
		('EMP003','KREETIKA CHOWDHURY','HYDERABAD',24000.00,'2016-11-07','D005'),
		('EMP004','TARUN HALDER','BHUBANESHWAR',21000,'2016-02-04','D004'),
		('EMP005','ANKITA SEN','THIRUVANANTHAPURAM',25000.00,'2022-01-26','D005'),
		('EMP006','ADITYA SHARMA','HYDERABAD',23000.00,'2022-01-26','D005'),
		('EMP007','ANUSHKA CHAKRABORTY','MUMBAI',25000.00,'2022-01-26','D005');

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;

SELECT EMP_NO,EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE 'A%';

SELECT DEPARTMENT.DEPT_NO,DEPT_NAME FROM DEPARTMENT WHERE DEPT_NO NOT IN (SELECT DEPT_NO FROM EMPLOYEE);

SELECT EMP_NO,EMP_NAME,CITY FROM EMPLOYEE WHERE SALARY IN (SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT DEPARTMENT.DEPT_NO,COUNT(EMP_NO) AS "TOTAL NO OF EMPLOYEE" FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_NO GROUP BY DEPT_NO ORDER BY DEPT_NO ASC;

SELECT DEPARTMENT.DEPT_NO,COUNT(EMP_NO) AS "TOTAL NO OF EMPLOYEE" FROM DEPARTMENT LEFT JOIN EMPLOYEE ON DEPARTMENT.DEPT_NO = EMPLOYEE.DEPT_NO GROUP BY DEPT_NO HAVING COUNT(EMP_NO) >= 0 ORDER BY DEPT_NO ASC;

